#!/bin/bash

echo "========================================="
echo "  Providence 后台 - 立即部署到 Railway"
echo "========================================="
echo ""
echo "🆔 项目 ID: 108ed0f8-b96d-418a-b105-108a59100fef"
echo "📍 项目位置: $(pwd)"
echo ""
echo "请按照以下步骤操作："
echo ""
echo "========================================="
echo "  【步骤 1】登录 Railway"
echo "========================================="
echo ""
echo "在新终端窗口中执行："
echo ""
echo "  railway login"
echo ""
echo "会打开浏览器，用 GitHub 账号登录"
echo ""
read -p "完成登录后，按回车继续..."
echo ""
echo "========================================="
echo "  【步骤 2】链接项目"
echo "========================================="
echo ""
echo "  railway link --project 108ed0f8-b96d-418a-b105-108a59100fef"
echo ""
read -p "按回车执行..."
railway link --project 108ed0f8-b96d-418a-b105-108a59100fef
echo ""
echo "========================================="
echo "  【步骤 3】部署到 Railway"
echo "========================================="
echo ""
echo "  railway up"
echo ""
read -p "按回车开始部署（需要3-5分钟）..."
railway up
echo ""
echo "========================================="
echo "  【步骤 4】获取域名"
echo "========================================="
echo ""
railway domain
echo ""
echo "========================================="
echo "  ✅ 部署完成！"
echo "========================================="
echo ""
echo "📝 接下来："
echo ""
echo "1. 复制上面显示的 Railway 域名"
echo "   （类似：xxx.up.railway.app）"
echo ""
echo "2. 在 Cloudflare 配置 DNS："
echo "   - 访问 Cloudflare"
echo "   - 域名: 4kp3l0iq.top"
echo "   - 添加 CNAME 记录："
echo "     类型: CNAME"
echo "     名称: admin"
echo "     目标: <刚才复制的Railway域名>"
echo "     代理: 已代理（橙色云朵）"
echo ""
echo "3. 在 Railway 绑定自定义域名："
echo "   - 访问: https://railway.app/project/108ed0f8-b96d-418a-b105-108a59100fef"
echo "   - Settings → Networking → Custom Domain"
echo "   - 输入: admin.4kp3l0iq.top"
echo ""
echo "4. 等待 2-5 分钟后访问："
echo "   https://admin.4kp3l0iq.top"
echo ""
echo "========================================="

